-- Fix missing columns needed for RxDB ↔ Supabase replication
-- 1. Add _deleted (soft-delete flag) to all synced tables
-- 2. Add updated_at to tables missing it

-- ── _deleted column (all 30 synced tables) ──
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE sub_tasks ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE daily_journal ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE vision_board ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE stressors ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE stressor_milestones ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE pomodoro_sessions ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE habit_completions ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE signals ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE portfolio_snapshots ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE family_events ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE morning_briefs ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE productivity_patterns ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE signal_weights ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE staff_members ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE staff_pay_periods ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE staff_expenses ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE staff_kpi_summaries ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE financial_accounts ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE financial_transactions ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE financial_subscriptions ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE financial_monthly_summaries ADD COLUMN IF NOT EXISTS _deleted BOOLEAN DEFAULT FALSE;

-- ── updated_at column (6 tables missing it) ──
ALTER TABLE habit_completions ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE portfolio_snapshots ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE morning_briefs ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE productivity_patterns ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE signal_weights ADD COLUMN IF NOT EXISTS updated_at TEXT;

-- ── created_at missing from projects ──
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_at TEXT;
